"""init: create database tables and indexes

Revision ID: 749575365b13
Revises: 
Create Date: 2026-07-22 15:47:29.705908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749575365b13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cycle_frequency', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'ARCHIVED', name='cyclestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('period_end >= period_start', name='check_cycle_dates'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpesa_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('mpesa_code', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sender_phone', sa.String(length=15), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'mpesa_code', name='uq_group_mpesa_code')
    )
    with op.batch_alter_table('mpesa_statements', schema=None) as batch_op:
        batch_op.create_index('idx_mpesa_reconcile', ['group_id', 'amount', 'sender_phone'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('TREASURER', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'phone_number', name='uq_group_phone')
    )
    op.create_table('contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('mpesa_statement_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('MPESA', 'CASH', 'BANK_TRANSFER', name='contributionmethod'), nullable=False),
    sa.Column('mpesa_code', sa.String(length=20), nullable=True),
    sa.Column('paid_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'LATE', 'FLAGGED', name='contributionstatus'), nullable=False),
    sa.Column('match_confidence', sa.Enum('EXACT', 'AMBIGUOUS', 'UNMATCHED', name='matchconfidence'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mpesa_statement_id'], ['mpesa_statements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'cycle_id', name='uq_member_cycle'),
    sa.UniqueConstraint('mpesa_statement_id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index('idx_contributions_cycle_status', ['cycle_id', 'status', 'amount'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISBURSED', 'CLEARED', 'DEFAULTED', name='loanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index('idx_loans_member_status', ['member_id', 'status'], unique=False)

    op.create_table('repayments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mpesa_code', sa.String(length=20), nullable=True),
    sa.Column('paid_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.create_index('idx_repayments_loan', ['loan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.drop_index('idx_repayments_loan')

    op.drop_table('repayments')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('idx_loans_member_status')

    op.drop_table('loans')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index('idx_contributions_cycle_status')

    op.drop_table('contributions')
    op.drop_table('users')
    with op.batch_alter_table('mpesa_statements', schema=None) as batch_op:
        batch_op.drop_index('idx_mpesa_reconcile')

    op.drop_table('mpesa_statements')
    op.drop_table('cycles')
    op.drop_table('groups')
    # ### end Alembic commands ###
